#!/usr/bin/env bash
# A script that runs an infinite loop and traps the SIGTERM signal

function invincible_handler() {
    echo "I am invincible!!!"
}

trap invincible_handler SIGTERM

while true
do
    echo "To infinity and beyond"
    sleep 2
done
